/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasIndexRouteImport } from './routes/obras/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIndexRoute = ObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/obras/': typeof ObrasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/obras': typeof ObrasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/obras/': typeof ObrasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/funcionarios' | '/login' | '/usuarios' | '/obras/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/funcionarios' | '/login' | '/usuarios' | '/obras'
  id: '__root__' | '/' | '/funcionarios' | '/login' | '/usuarios' | '/obras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FuncionariosRoute: typeof FuncionariosRoute
  LoginRoute: typeof LoginRoute
  UsuariosRoute: typeof UsuariosRoute
  ObrasIndexRoute: typeof ObrasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/': {
      id: '/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof ObrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FuncionariosRoute: FuncionariosRoute,
  LoginRoute: LoginRoute,
  UsuariosRoute: UsuariosRoute,
  ObrasIndexRoute: ObrasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
